// ═══════════════════════════════════════════════════════════════════════════════
// SIMULATIONS PHET INTERACTIVES — PhET Interactive Simulations, University of Colorado
// Intégrées nativement dans SmartSchool SN pour les matières scientifiques
// Source : https://phet.colorado.edu  |  Licence : CC BY 4.0
// Niveaux : 3e · 2nde · 1ère · Terminale (S1, S2, L1, L2)
// ═══════════════════════════════════════════════════════════════════════════════

export interface PhetSimulation {
  id: string
  titre: string
  description: string
  matiere: 'Mathématiques' | 'Physique' | 'Chimie' | 'Physique-Chimie' | 'SVT' | 'Sciences'
  niveaux: Array<'3e' | '2nde' | '1ère' | 'Terminale' | 'Terminale S1' | 'Terminale S2' | 'Terminale L1' | 'Terminale L2'>
  series?: Array<'S1' | 'S2' | 'L1' | 'L2' | 'STEG' | 'Toutes'>
  themes: string[]
  embedUrl: string
  difficulte: 'decouverte' | 'intermediaire' | 'avance'
}

const PHET_BASE = 'https://phet.colorado.edu/sims/html'
function sim(slug: string): string {
  return `${PHET_BASE}/${slug}/latest/${slug}_fr.html`
}

// ═══════════════════════════════════════════════════════════════════════════════
// MATHÉMATIQUES
// ═══════════════════════════════════════════════════════════════════════════════

const MATHS: PhetSimulation[] = [
  {
    id: 'graphing-lines',
    titre: 'Tracer des droites',
    description: 'Explorez la relation entre équation réduite et représentation graphique. Variez pente et ordonnée à l\'origine.',
    matiere: 'Mathématiques',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Fonctions affines', 'Droites', 'Graphiques'],
    embedUrl: sim('graphing-lines'),
    difficulte: 'decouverte',
  },
  {
    id: 'graphing-quadratics',
    titre: 'Graphiques Quadratiques',
    description: 'Explorez les fonctions du second degré. Observez l\'effet des coefficients a, b, c sur la parabole.',
    matiere: 'Mathématiques',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Fonctions du 2nd degré', 'Parabole', 'Discriminant'],
    embedUrl: sim('graphing-quadratics'),
    difficulte: 'intermediaire',
  },
  {
    id: 'graphing-slope-intercept',
    titre: 'Représenter à partir de l\'équation réduite',
    description: 'Maîtrisez la forme y = mx + b. Connectez les représentations algébrique et graphique.',
    matiere: 'Mathématiques',
    niveaux: ['3e', '2nde'],
    series: ['Toutes'],
    themes: ['Fonctions affines', 'Pente', 'Équation de droite'],
    embedUrl: sim('graphing-slope-intercept'),
    difficulte: 'decouverte',
  },
  {
    id: 'function-builder',
    titre: 'Constructeur de fonctions',
    description: 'Composez des fonctions et explorez leurs propriétés : images, antécédents, compositions.',
    matiere: 'Mathématiques',
    niveaux: ['2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'L1', 'L2'],
    themes: ['Fonctions', 'Composition', 'Représentation'],
    embedUrl: sim('function-builder'),
    difficulte: 'intermediaire',
  },
  {
    id: 'calculus-grapher',
    titre: 'Traceur de graphiques de calcul',
    description: 'Visualisez les dérivées et primitives. Tracez f, f\' et F et observez leurs relations.',
    matiere: 'Mathématiques',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Dérivées', 'Primitives', 'Intégration'],
    embedUrl: sim('calculus-grapher'),
    difficulte: 'avance',
  },
  {
    id: 'trig-tour',
    titre: 'Tour de trigonométrie',
    description: 'Explorez sin, cos, tan sur le cercle trigonométrique. Visualisez les valeurs remarquables.',
    matiere: 'Mathématiques',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Trigonométrie', 'Cercle trigonométrique', 'Angles'],
    embedUrl: sim('trig-tour'),
    difficulte: 'intermediaire',
  },
  {
    id: 'vector-addition',
    titre: 'Addition de vecteurs',
    description: 'Additionnez des vecteurs graphiquement et algébriquement. Visualisez les composantes.',
    matiere: 'Mathématiques',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Vecteurs', 'Géométrie vectorielle', 'Composantes'],
    embedUrl: sim('vector-addition'),
    difficulte: 'intermediaire',
  },
  {
    id: 'vector-addition-equations',
    titre: 'Addition de vecteurs : Équations',
    description: 'Résolvez des équations vectorielles. Décomposez des vecteurs en composantes x et y.',
    matiere: 'Mathématiques',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Vecteurs', 'Équations vectorielles', 'Décomposition'],
    embedUrl: sim('vector-addition-equations'),
    difficulte: 'avance',
  },
  {
    id: 'least-squares-regression',
    titre: 'Régression des moindres carrés',
    description: 'Tracez une courbe de tendance sur un nuage de points. Calculez le coefficient de corrélation.',
    matiere: 'Mathématiques',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2', 'STEG'],
    themes: ['Statistiques', 'Régression', 'Corrélation'],
    embedUrl: sim('least-squares-regression'),
    difficulte: 'avance',
  },
  {
    id: 'curve-fitting',
    titre: 'Ajustement des Courbes',
    description: 'Ajustez un polynôme sur un ensemble de données. Explorez le degré et ses effets.',
    matiere: 'Mathématiques',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Polynômes', 'Interpolation', 'Approximation'],
    embedUrl: sim('curve-fitting'),
    difficulte: 'avance',
  },
  {
    id: 'plinko-probability',
    titre: 'Probabilité avec un plinko',
    description: 'Simulez des expériences aléatoires et construisez des distributions de probabilités.',
    matiere: 'Mathématiques',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2', 'STEG'],
    themes: ['Probabilités', 'Loi binomiale', 'Statistiques'],
    embedUrl: sim('plinko-probability'),
    difficulte: 'intermediaire',
  },
  {
    id: 'area-model-algebra',
    titre: 'Modélisation par les aires - Algèbre',
    description: 'Développez et factorisez des expressions algébriques par le modèle géométrique des aires.',
    matiere: 'Mathématiques',
    niveaux: ['3e', '2nde'],
    series: ['Toutes'],
    themes: ['Algèbre', 'Factorisation', 'Développement'],
    embedUrl: sim('area-model-algebra'),
    difficulte: 'decouverte',
  },
  {
    id: 'equality-explorer',
    titre: 'Explorateur d\'égalité',
    description: 'Équilibrez des balances et résolvez des équations linéaires visuellement.',
    matiere: 'Mathématiques',
    niveaux: ['3e', '2nde'],
    series: ['Toutes'],
    themes: ['Équations', 'Résolution', 'Équilibre'],
    embedUrl: sim('equality-explorer'),
    difficulte: 'decouverte',
  },
  {
    id: 'fourier-making-waves',
    titre: 'Fourier : Faire des ondes',
    description: 'Décomposez et recomposez des signaux par séries de Fourier. Visualisez les harmoniques.',
    matiere: 'Mathématiques',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Séries de Fourier', 'Ondes', 'Décomposition spectrale'],
    embedUrl: sim('fourier-making-waves'),
    difficulte: 'avance',
  },
]

// ═══════════════════════════════════════════════════════════════════════════════
// PHYSIQUE
// ═══════════════════════════════════════════════════════════════════════════════

const PHYSIQUE: PhetSimulation[] = [
  // ── Mécanique ──
  {
    id: 'forces-and-motion-basics',
    titre: 'Forces et mouvement : les bases',
    description: 'Appliquez des forces, observez accélération et vitesse. Explorez la 2ème loi de Newton.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['Forces', 'Lois de Newton', 'Mouvement'],
    embedUrl: sim('forces-and-motion-basics'),
    difficulte: 'decouverte',
  },
  {
    id: 'projectile-motion',
    titre: 'Mouvement d\'un projectile',
    description: 'Lancez des projectiles et observez les trajectoires paraboliques. Variez angle, vitesse, masse.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Cinématique', 'Projectiles', 'Parabole de sécurité'],
    embedUrl: sim('projectile-motion'),
    difficulte: 'intermediaire',
  },
  {
    id: 'projectile-data-lab',
    titre: 'Labo de données sur les projectiles',
    description: 'Collectez des données expérimentales sur des projectiles. Analysez et modélisez les trajectoires.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Cinématique', 'Mesures', 'Modélisation'],
    embedUrl: sim('projectile-data-lab'),
    difficulte: 'avance',
  },
  {
    id: 'collision-lab',
    titre: 'Labo de Collisions',
    description: 'Explorez les collisions élastiques et inélastiques. Vérifiez la conservation de la quantité de mouvement.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Dynamique', 'Quantité de mouvement', 'Chocs'],
    embedUrl: sim('collision-lab'),
    difficulte: 'intermediaire',
  },
  {
    id: 'energy-forms-and-changes',
    titre: 'Formes d\'énergie et conversions',
    description: 'Visualisez les différentes formes d\'énergie et leurs conversions : cinétique, potentielle, thermique.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Énergie', 'Conversions', 'Conservation'],
    embedUrl: sim('energy-forms-and-changes'),
    difficulte: 'decouverte',
  },
  {
    id: 'energy-skate-park',
    titre: 'Énergie au Skate Park',
    description: 'Explorez la conservation de l\'énergie mécanique. Observez les échanges Ec/Ep avec frottements.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Énergie mécanique', 'Conservation', 'Frottements'],
    embedUrl: sim('energy-skate-park'),
    difficulte: 'intermediaire',
  },
  {
    id: 'friction',
    titre: 'Frottements',
    description: 'Explorez les forces de frottement statique et cinétique. Mesurez les coefficients de frottement.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Forces', 'Frottements', 'Coefficient'],
    embedUrl: sim('friction'),
    difficulte: 'decouverte',
  },
  {
    id: 'masses-and-springs',
    titre: 'Masses et Ressorts',
    description: 'Étudiez les oscillations masse-ressort. Mesurez période, fréquence et constante de raideur.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Oscillations', 'Loi de Hooke', 'Dynamique'],
    embedUrl: sim('masses-and-springs'),
    difficulte: 'intermediaire',
  },
  {
    id: 'hookes-law',
    titre: 'La loi de Hooke',
    description: 'Vérifiez la proportionnalité force-déformation. Déterminez la constante de raideur d\'un ressort.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Mécanique', 'Ressorts', 'Élasticité'],
    embedUrl: sim('hookes-law'),
    difficulte: 'decouverte',
  },
  {
    id: 'pendulum-lab',
    titre: 'Labo du pendule',
    description: 'Étudiez les oscillations d\'un pendule simple. Mesurez la période en fonction de la longueur et de g.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['Oscillations', 'Pendule', 'Période'],
    embedUrl: sim('pendulum-lab'),
    difficulte: 'intermediaire',
  },
  {
    id: 'gravity-and-orbits',
    titre: 'Gravité et orbites',
    description: 'Simulez le mouvement des planètes et satellites. Explorez la loi de la gravitation universelle.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['Gravitation', 'Orbites', 'Kepler'],
    embedUrl: sim('gravity-and-orbits'),
    difficulte: 'intermediaire',
  },
  {
    id: 'gravity-force-lab',
    titre: 'Labo Attraction Gravitationnelle',
    description: 'Mesurez la force gravitationnelle entre deux masses. Vérifiez la loi de Newton.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Gravitation universelle', 'Forces', 'Newton'],
    embedUrl: sim('gravity-force-lab'),
    difficulte: 'avance',
  },
  {
    id: 'keplers-laws',
    titre: 'Lois de Kepler',
    description: 'Visualisez les trois lois de Kepler sur les orbites planétaires. Mesurez les périodes.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Kepler', 'Orbites', 'Mouvement planétaire'],
    embedUrl: sim('keplers-laws'),
    difficulte: 'avance',
  },
  {
    id: 'under-pressure',
    titre: 'Sous Pression',
    description: 'Explorez la pression dans les fluides. Vérifiez la loi fondamentale de l\'hydrostatique.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['Fluides', 'Pression', 'Hydrostatique'],
    embedUrl: sim('under-pressure'),
    difficulte: 'intermediaire',
  },
  {
    id: 'buoyancy',
    titre: 'Poussée d\'Archimède',
    description: 'Explorez le principe d\'Archimède. Mesurez la poussée en fonction du volume immergé et de la densité.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['Fluides', 'Archimède', 'Poussée'],
    embedUrl: sim('buoyancy'),
    difficulte: 'decouverte',
  },
  {
    id: 'density',
    titre: 'Masse volumique',
    description: 'Mesurez les masses volumiques de différents matériaux. Reliez densité, masse et volume.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde'],
    series: ['Toutes'],
    themes: ['Masse volumique', 'Densité', 'Mesures'],
    embedUrl: sim('density'),
    difficulte: 'decouverte',
  },

  // ── Électricité ──
  {
    id: 'circuit-construction-kit-dc',
    titre: 'Construire un circuit : Courant Continu',
    description: 'Construisez des circuits électriques CC. Mesurez tensions et courants. Loi d\'Ohm en pratique.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['Circuits électriques', 'Courant continu', 'Loi d\'Ohm'],
    embedUrl: sim('circuit-construction-kit-dc'),
    difficulte: 'decouverte',
  },
  {
    id: 'circuit-construction-kit-ac',
    titre: 'Kit de construction de circuits : Tension alternative',
    description: 'Analysez les circuits RC, RL, RLC en régime sinusoïdal. Mesurez déphasages et impédances.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Circuits AC', 'Oscillations électriques', 'Résonance'],
    embedUrl: sim('circuit-construction-kit-ac'),
    difficulte: 'avance',
  },
  {
    id: 'ohms-law',
    titre: 'Loi d\'Ohm',
    description: 'Vérifiez la relation U = RI. Observez les effets de R sur I pour une tension donnée.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Loi d\'Ohm', 'Résistance', 'Circuits'],
    embedUrl: sim('ohms-law'),
    difficulte: 'decouverte',
  },
  {
    id: 'resistance-in-a-wire',
    titre: 'Résistance dans un fil',
    description: 'Explorez comment la longueur, la section et la résistivité influencent la résistance d\'un conducteur.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Résistance', 'Conducteurs', 'Résistivité'],
    embedUrl: sim('resistance-in-a-wire'),
    difficulte: 'decouverte',
  },
  {
    id: 'capacitor-lab-basics',
    titre: 'Labo du condensateur',
    description: 'Chargez et déchargez un condensateur. Explorez capacité, charge, tension et énergie stockée.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Condensateur', 'Énergie électrique', 'RC'],
    embedUrl: sim('capacitor-lab-basics'),
    difficulte: 'intermediaire',
  },
  {
    id: 'charges-and-fields',
    titre: 'Charges et champs électriques',
    description: 'Visualisez le champ électrique créé par des charges ponctuelles. Tracez les lignes de champ.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Électrostatique', 'Champ électrique', 'Potentiel'],
    embedUrl: sim('charges-and-fields'),
    difficulte: 'intermediaire',
  },
  {
    id: 'coulombs-law',
    titre: 'Loi de Coulomb',
    description: 'Mesurez la force électrostatique entre deux charges. Vérifiez la dépendance en 1/r².',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Électrostatique', 'Loi de Coulomb', 'Forces'],
    embedUrl: sim('coulombs-law'),
    difficulte: 'avance',
  },
  {
    id: 'balloons-and-static-electricity',
    titre: 'Ballons et Électricité statique',
    description: 'Chargez des ballons par frottement et observez les phénomènes d\'électrostatique.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde'],
    series: ['Toutes'],
    themes: ['Électrostatique', 'Charges', 'Frottement'],
    embedUrl: sim('balloons-and-static-electricity'),
    difficulte: 'decouverte',
  },
  {
    id: 'faradays-electromagnetic-lab',
    titre: 'Labo électromagnétique de Faraday',
    description: 'Explorez l\'induction électromagnétique. Créez un courant en bougeant un aimant.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Induction', 'Électromagnétisme', 'Loi de Faraday'],
    embedUrl: sim('faradays-electromagnetic-lab'),
    difficulte: 'intermediaire',
  },
  {
    id: 'faradays-law',
    titre: 'La loi de Faraday',
    description: 'Visualisez le flux magnétique et la f.e.m. induite. Comprenez le sens du courant induit.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Induction', 'Loi de Faraday', 'Flux magnétique'],
    embedUrl: sim('faradays-law'),
    difficulte: 'avance',
  },
  {
    id: 'generator',
    titre: 'Générateur électrique',
    description: 'Explorez le fonctionnement d\'un générateur : alternateur et dynamo. Visualisez le courant induit.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Générateur', 'Induction', 'Alternateur'],
    embedUrl: sim('generator'),
    difficulte: 'intermediaire',
  },
  {
    id: 'magnets-and-electromagnets',
    titre: 'Aimants et électro-aimants',
    description: 'Explorez le champ magnétique des aimants et électro-aimants. Visualisez les lignes de champ.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Magnétisme', 'Champ magnétique', 'Électro-aimant'],
    embedUrl: sim('magnets-and-electromagnets'),
    difficulte: 'decouverte',
  },
  {
    id: 'magnet-and-compass',
    titre: 'Aimant et boussole',
    description: 'Observez comment un aimant oriente une boussole. Explorez le champ magnétique terrestre.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde'],
    series: ['Toutes'],
    themes: ['Magnétisme', 'Boussole', 'Champ magnétique'],
    embedUrl: sim('magnet-and-compass'),
    difficulte: 'decouverte',
  },

  // ── Optique ──
  {
    id: 'bending-light',
    titre: 'Déviation de la lumière',
    description: 'Explorez la réfraction et la réflexion de la lumière. Vérifiez les lois de Snell-Descartes.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['Optique', 'Réfraction', 'Snell-Descartes'],
    embedUrl: sim('bending-light'),
    difficulte: 'intermediaire',
  },
  {
    id: 'geometric-optics',
    titre: 'Optique géométrique',
    description: 'Formez des images avec des lentilles convergentes et divergentes. Construisez les rayons lumineux.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Lentilles', 'Images', 'Vergence'],
    embedUrl: sim('geometric-optics'),
    difficulte: 'intermediaire',
  },
  {
    id: 'color-vision',
    titre: 'Vision des couleurs',
    description: 'Explorez la synthèse additive et soustractive des couleurs. Comprenez la perception visuelle.',
    matiere: 'Physique',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Lumière', 'Couleurs', 'Synthèse'],
    embedUrl: sim('color-vision'),
    difficulte: 'decouverte',
  },
  {
    id: 'wave-interference',
    titre: 'Interférences',
    description: 'Observez les interférences d\'ondes mécaniques et lumineuses. Explorez les conditions d\'interférences.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Ondes', 'Interférences', 'Diffraction'],
    embedUrl: sim('wave-interference'),
    difficulte: 'avance',
  },
  {
    id: 'wave-on-a-string',
    titre: 'Onde sur une corde',
    description: 'Visualisez la propagation des ondes mécaniques. Explorez amplitude, fréquence, longueur d\'onde.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Ondes mécaniques', 'Propagation', 'Réflexion'],
    embedUrl: sim('wave-on-a-string'),
    difficulte: 'intermediaire',
  },
  {
    id: 'blackbody-spectrum',
    titre: 'Spectre du corps noir',
    description: 'Explorez le rayonnement thermique. Reliez température et spectre d\'émission.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Rayonnement', 'Thermodynamique', 'Spectre'],
    embedUrl: sim('blackbody-spectrum'),
    difficulte: 'avance',
  },

  // ── Thermodynamique ──
  {
    id: 'gas-properties',
    titre: 'Propriétés des gaz',
    description: 'Explorez les lois des gaz parfaits. Observez pression, volume et température dans une enceinte.',
    matiere: 'Physique',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Gaz parfaits', 'Loi de Boyle-Mariotte', 'Thermodynamique'],
    embedUrl: sim('gas-properties'),
    difficulte: 'intermediaire',
  },
  {
    id: 'diffusion',
    titre: 'Diffusion d\'un gaz',
    description: 'Observez la diffusion de molécules gazeuses. Explorez l\'effet de la masse et de la température.',
    matiere: 'Physique',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Diffusion', 'Gaz', 'Mouvement brownien'],
    embedUrl: sim('diffusion'),
    difficulte: 'intermediaire',
  },
]

// ═══════════════════════════════════════════════════════════════════════════════
// CHIMIE
// ═══════════════════════════════════════════════════════════════════════════════

const CHIMIE: PhetSimulation[] = [
  {
    id: 'build-an-atom',
    titre: 'Construire un atome',
    description: 'Construisez des atomes en ajoutant protons, neutrons et électrons. Identifiez l\'élément et sa stabilité.',
    matiere: 'Chimie',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Structure atomique', 'Tableau périodique', 'Isotopes'],
    embedUrl: sim('build-an-atom'),
    difficulte: 'decouverte',
  },
  {
    id: 'isotopes-and-atomic-mass',
    titre: 'Isotopes et Masse Atomique',
    description: 'Explorez les isotopes et calculez la masse atomique moyenne. Comprenez l\'abondance naturelle.',
    matiere: 'Chimie',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Isotopes', 'Masse atomique', 'Noyau'],
    embedUrl: sim('isotopes-and-atomic-mass'),
    difficulte: 'intermediaire',
  },
  {
    id: 'build-a-nucleus',
    titre: 'Construire un noyau',
    description: 'Explorez la stabilité nucléaire. Comprenez la radioactivité alpha, bêta et gamma.',
    matiere: 'Chimie',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Radioactivité', 'Noyau atomique', 'Désintégration'],
    embedUrl: sim('build-a-nucleus'),
    difficulte: 'avance',
  },
  {
    id: 'rutherford-scattering',
    titre: 'Diffusion de Rutherford',
    description: 'Reproduisez l\'expérience de Rutherford. Comprenez la découverte du noyau atomique.',
    matiere: 'Chimie',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Structure atomique', 'Expérience de Rutherford', 'Noyau'],
    embedUrl: sim('rutherford-scattering'),
    difficulte: 'avance',
  },
  {
    id: 'models-of-the-hydrogen-atom',
    titre: 'Modèle de l\'atome d\'hydrogène',
    description: 'Comparez les modèles atomiques de Bohr à la mécanique quantique. Observez les spectres d\'émission.',
    matiere: 'Chimie',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Modèle atomique', 'Spectres', 'Bohr'],
    embedUrl: sim('models-of-the-hydrogen-atom'),
    difficulte: 'avance',
  },
  {
    id: 'build-a-molecule',
    titre: 'Créer une molécule',
    description: 'Assemblez des atomes pour former des molécules. Explorez les liaisons covalentes et les formules.',
    matiere: 'Chimie',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Liaisons chimiques', 'Molécules', 'Formules chimiques'],
    embedUrl: sim('build-a-molecule'),
    difficulte: 'decouverte',
  },
  {
    id: 'molecule-shapes',
    titre: 'Formes des Molécules',
    description: 'Prédisez la géométrie des molécules par la méthode VSEPR. Visualisez en 3D.',
    matiere: 'Chimie',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['VSEPR', 'Géométrie moléculaire', 'Liaisons'],
    embedUrl: sim('molecule-shapes'),
    difficulte: 'intermediaire',
  },
  {
    id: 'molecule-polarity',
    titre: 'Polarité des Molécules',
    description: 'Explorez la polarité des liaisons et des molécules. Comprendre les moments dipolaires.',
    matiere: 'Chimie',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Polarité', 'Électronégativité', 'Liaisons'],
    embedUrl: sim('molecule-polarity'),
    difficulte: 'avance',
  },
  {
    id: 'molecules-and-light',
    titre: 'Molécules et lumière',
    description: 'Explorez l\'interaction entre molécules et rayonnement. Effet de serre à l\'échelle moléculaire.',
    matiere: 'Chimie',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Spectroscopie', 'Liaison chimique', 'Effet de serre'],
    embedUrl: sim('molecules-and-light'),
    difficulte: 'intermediaire',
  },
  {
    id: 'acid-base-solutions',
    titre: 'Solutions acido-basiques',
    description: 'Comparez acides forts et faibles. Mesurez le pH et la conductivité. Explorez les équilibres.',
    matiere: 'Chimie',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Acides-bases', 'pH', 'Équilibre chimique'],
    embedUrl: sim('acid-base-solutions'),
    difficulte: 'intermediaire',
  },
  {
    id: 'ph-scale',
    titre: 'Échelle de pH',
    description: 'Mesurez le pH de différentes solutions. Comprenez la relation entre pH et concentration en H⁺.',
    matiere: 'Chimie',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['S1', 'S2', 'Toutes'],
    themes: ['pH', 'Acides-bases', 'Concentration'],
    embedUrl: sim('ph-scale'),
    difficulte: 'decouverte',
  },
  {
    id: 'concentration',
    titre: 'Concentration',
    description: 'Préparez des solutions de différentes concentrations. Explorez la dissolution et la dilution.',
    matiere: 'Chimie',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Concentration', 'Dissolution', 'Dilution'],
    embedUrl: sim('concentration'),
    difficulte: 'decouverte',
  },
  {
    id: 'molarity',
    titre: 'Concentration molaire',
    description: 'Calculez et visualisez la molarité de solutions. Réalisez des dilutions et des mélanges.',
    matiere: 'Chimie',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Molarité', 'Stœchiométrie', 'Solutions'],
    embedUrl: sim('molarity'),
    difficulte: 'intermediaire',
  },
  {
    id: 'beers-law-lab',
    titre: 'Laboratoire Loi de Beer-Lambert',
    description: 'Explorez la spectrophotométrie. Établissez la relation absorbance-concentration.',
    matiere: 'Chimie',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Spectrophotométrie', 'Beer-Lambert', 'Dosage colorimétrique'],
    embedUrl: sim('beers-law-lab'),
    difficulte: 'avance',
  },
  {
    id: 'reactants-products-and-leftovers',
    titre: 'Réactifs, Produits et Restes',
    description: 'Identifiez le réactif limitant dans une réaction. Calculez les quantités de produits formés.',
    matiere: 'Chimie',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Stœchiométrie', 'Réactif limitant', 'Bilan de réaction'],
    embedUrl: sim('reactants-products-and-leftovers'),
    difficulte: 'intermediaire',
  },
  {
    id: 'balancing-chemical-equations',
    titre: 'Ajuster des Équations Chimiques',
    description: 'Équilibrez des équations chimiques en ajustant les coefficients stœchiométriques.',
    matiere: 'Chimie',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Équations chimiques', 'Stœchiométrie', 'Conservation'],
    embedUrl: sim('balancing-chemical-equations'),
    difficulte: 'decouverte',
  },
  {
    id: 'states-of-matter',
    titre: 'États de la matière',
    description: 'Explorez les transitions de phase solide-liquide-gaz à l\'échelle moléculaire.',
    matiere: 'Chimie',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['États de la matière', 'Transitions de phase', 'Interactions moléculaires'],
    embedUrl: sim('states-of-matter'),
    difficulte: 'intermediaire',
  },
  {
    id: 'atomic-interactions',
    titre: 'Interactions atomiques',
    description: 'Explorez les forces interatomiques : attraction de Van der Waals et répulsion. Énergie potentielle.',
    matiere: 'Chimie',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2'],
    themes: ['Liaisons chimiques', 'Interactions', 'Énergie'],
    embedUrl: sim('atomic-interactions'),
    difficulte: 'avance',
  },
]

// ═══════════════════════════════════════════════════════════════════════════════
// SVT / BIOLOGIE
// ═══════════════════════════════════════════════════════════════════════════════

const SVT: PhetSimulation[] = [
  {
    id: 'membrane-channels',
    titre: 'Transport membranaire',
    description: 'Visualisez la diffusion et le transport actif à travers les membranes cellulaires.',
    matiere: 'SVT',
    niveaux: ['1ère', 'Terminale', 'Terminale S1', 'Terminale S2'],
    series: ['S1', 'S2', 'L1', 'L2'],
    themes: ['Membranes cellulaires', 'Osmose', 'Transport actif'],
    embedUrl: sim('membrane-channels'),
    difficulte: 'intermediaire',
  },
  {
    id: 'neuron',
    titre: 'Neurone',
    description: 'Explorez la transmission du signal nerveux. Visualisez le potentiel d\'action.',
    matiere: 'SVT',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2', 'Terminale L1', 'Terminale L2'],
    series: ['S1', 'S2', 'L1', 'L2'],
    themes: ['Système nerveux', 'Potentiel d\'action', 'Synapse'],
    embedUrl: sim('neuron'),
    difficulte: 'avance',
  },
  {
    id: 'gene-expression-essentials',
    titre: 'Expression des gènes',
    description: 'Visualisez la transcription et la traduction. De l\'ADN à la protéine.',
    matiere: 'SVT',
    niveaux: ['Terminale', 'Terminale S1', 'Terminale S2', 'Terminale L1', 'Terminale L2'],
    series: ['S1', 'S2', 'L1', 'L2'],
    themes: ['Génétique moléculaire', 'ADN', 'Protéines'],
    embedUrl: sim('gene-expression-essentials'),
    difficulte: 'avance',
  },
  {
    id: 'natural-selection',
    titre: 'Sélection naturelle',
    description: 'Simulez l\'évolution par sélection naturelle. Observez la variation des traits au fil des générations.',
    matiere: 'SVT',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Évolution', 'Sélection naturelle', 'Génétique'],
    embedUrl: sim('natural-selection'),
    difficulte: 'decouverte',
  },
  {
    id: 'greenhouse-effect',
    titre: 'Effet de serre',
    description: 'Visualisez l\'effet de serre et le réchauffement climatique. Comprenez le rôle des gaz à effet de serre.',
    matiere: 'SVT',
    niveaux: ['3e', '2nde', '1ère', 'Terminale'],
    series: ['Toutes'],
    themes: ['Climatologie', 'Effet de serre', 'Écologie'],
    embedUrl: sim('greenhouse-effect'),
    difficulte: 'decouverte',
  },
  {
    id: 'my-solar-system',
    titre: 'Mon Système Solaire',
    description: 'Simulez le mouvement des corps célestes. Explorez les orbites et la gravitation.',
    matiere: 'SVT',
    niveaux: ['3e', '2nde', '1ère'],
    series: ['Toutes'],
    themes: ['Astronomie', 'Système solaire', 'Orbites'],
    embedUrl: sim('my-solar-system'),
    difficulte: 'decouverte',
  },
]

// ═══════════════════════════════════════════════════════════════════════════════
// CATALOGUE COMPLET
// ═══════════════════════════════════════════════════════════════════════════════

export const PHET_SIMULATIONS: PhetSimulation[] = [
  ...MATHS,
  ...PHYSIQUE,
  ...CHIMIE,
  ...SVT,
]

// ── Helpers de filtrage ──────────────────────────────────────────────────────

export function getPhetByMatiere(matiere: PhetSimulation['matiere']): PhetSimulation[] {
  return PHET_SIMULATIONS.filter(s => s.matiere === matiere)
}

export function getPhetByNiveau(niveau: string): PhetSimulation[] {
  return PHET_SIMULATIONS.filter(s => s.niveaux.some(n => n.includes(niveau)))
}

export function getPhetByNiveauAndMatiere(niveau: string, matiere: PhetSimulation['matiere']): PhetSimulation[] {
  return PHET_SIMULATIONS.filter(s =>
    s.matiere === matiere &&
    s.niveaux.some(n => n.includes(niveau))
  )
}

export function searchPhet(query: string): PhetSimulation[] {
  const q = query.toLowerCase()
  return PHET_SIMULATIONS.filter(s =>
    s.titre.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.themes.some(t => t.toLowerCase().includes(q))
  )
}

// ── Statistiques ─────────────────────────────────────────────────────────────

export const PHET_STATS = {
  total: PHET_SIMULATIONS.length,
  parMatiere: {
    Mathématiques: MATHS.length,
    Physique: PHYSIQUE.length,
    Chimie: CHIMIE.length,
    SVT: SVT.length,
  },
  niveaux: ['3e', '2nde', '1ère', 'Terminale'],
  series: ['S1', 'S2', 'L1', 'L2'],
} as const
