/**
 * Donnees mock -- 12 lecons de demonstration SmartSchool Hub
 * Videos : Khan Academy FR / contenus educatifs libres
 */

import type { Lesson } from '@/types/hub'

export const MOCK_LESSONS: Lesson[] = [
  {
    id: 'hub-001',
    title: 'Les fonctions du second degre',
    description: "Definition, forme canonique, discriminant et resolution d'equations ax2+bx+c=0. Exemples corriges niveau Terminale.",
    subject: 'maths',
    niveau: 'terminale',
    teacher: { name: 'M. Diallo' },
    videoUrl: 'https://www.youtube.com/embed/2ZzuZvz33X0',
    durationSec: 1140,
    thumbnailUrl: 'https://i.ytimg.com/vi/2ZzuZvz33X0/hqdefault.jpg',
    views: 4820,
    isTrending: true,
    resources: [
      { kind: 'pdf',       title: 'Fiche resume -- 2nd degre',    url: '#' },
      { kind: 'exercices', title: "Series d'exercices corriges",   url: '#' },
    ],
    chapters: [
      { label: 'Introduction',           atSec: 0   },
      { label: 'Forme canonique',        atSec: 180 },
      { label: 'Discriminant',           atSec: 420 },
      { label: 'Applications pratiques', atSec: 780 },
    ],
  },
  {
    id: 'hub-002',
    title: 'La cellule eucaryote -- Structure et organites',
    description: "Organisation de la cellule animale et vegetale, role du noyau, des mitochondries et du reticulum endoplasmique.",
    subject: 'svt',
    niveau: 'premiere',
    teacher: { name: 'Mme Ndiaye' },
    videoUrl: 'https://www.youtube.com/embed/URUJD5NEXC8',
    durationSec: 960,
    thumbnailUrl: 'https://i.ytimg.com/vi/URUJD5NEXC8/hqdefault.jpg',
    views: 3210,
    isNew: true,
    resources: [
      { kind: 'pdf',  title: 'Schema annote de la cellule', url: '#' },
      { kind: 'quiz', title: 'Quiz 10 questions',           url: '#' },
    ],
    chapters: [
      { label: 'Rappels : cellule procaryote', atSec: 0   },
      { label: 'Le noyau',                     atSec: 240 },
      { label: 'Mitochondries et ATP',         atSec: 540 },
      { label: 'Cellule vegetale',             atSec: 780 },
    ],
  },
  {
    id: 'hub-003',
    title: 'Lois de Newton -- Mecanique classique',
    description: "Principes d'inertie, fondamental de la dynamique et interactions. Exercices avec bilan des forces.",
    subject: 'pc',
    niveau: 'terminale',
    teacher: { name: 'M. Sow' },
    videoUrl: 'https://www.youtube.com/embed/kKKM8Y-u7ds',
    durationSec: 1320,
    thumbnailUrl: 'https://i.ytimg.com/vi/kKKM8Y-u7ds/hqdefault.jpg',
    views: 5670,
    isTrending: true,
    resources: [
      { kind: 'pdf',       title: 'Formulaire mecanique',     url: '#' },
      { kind: 'exercices', title: 'Problemes avec solutions',  url: '#' },
    ],
    chapters: [
      { label: "1ere loi -- Inertie",    atSec: 0   },
      { label: "2eme loi -- F = ma",     atSec: 360 },
      { label: "3eme loi -- Reciprocite", atSec: 720 },
      { label: 'Exercices corriges',     atSec: 960 },
    ],
  },
  {
    id: 'hub-004',
    title: 'Le cogito de Descartes -- Introduction a la philosophie',
    description: "Je pense donc je suis : analyse du doute methodique, fondement de la certitude et dualisme corps-esprit.",
    subject: 'philo',
    niveau: 'terminale',
    teacher: { name: 'M. Ba' },
    videoUrl: 'https://www.youtube.com/embed/CAjWUrwvxs4',
    durationSec: 840,
    thumbnailUrl: 'https://i.ytimg.com/vi/CAjWUrwvxs4/hqdefault.jpg',
    views: 2380,
    isNew: true,
    resources: [
      { kind: 'pdf',  title: 'Extrait des Meditations',  url: '#' },
      { kind: 'quiz', title: 'Commentaire guide',         url: '#' },
    ],
    chapters: [
      { label: 'Le doute methodique', atSec: 0   },
      { label: 'Le cogito ergo sum',  atSec: 300 },
      { label: 'Dualisme cartesien',  atSec: 600 },
    ],
  },
  {
    id: 'hub-005',
    title: "L'Afrique precoloniale -- Royaumes et empires",
    description: "Empire du Mali, Songhai, Royaume du Senegal. Structures politiques et sociales avant la colonisation.",
    subject: 'hg',
    niveau: '3e',
    teacher: { name: 'Mme Faye' },
    videoUrl: 'https://www.youtube.com/embed/v8eKU7Yp4bI',
    durationSec: 1080,
    thumbnailUrl: 'https://i.ytimg.com/vi/v8eKU7Yp4bI/hqdefault.jpg',
    views: 1940,
    resources: [
      { kind: 'pdf',  title: 'Cartes et chronologie', url: '#' },
      { kind: 'quiz', title: 'QCM 15 questions',       url: '#' },
    ],
    chapters: [
      { label: "L'Empire du Mali",       atSec: 0   },
      { label: "L'Empire Songhai",       atSec: 360 },
      { label: 'Le Senegal precolonial', atSec: 720 },
    ],
  },
  {
    id: 'hub-006',
    title: 'La narration au passe -- Imparfait et passe simple',
    description: "Distinguer l'imparfait du passe simple dans un recit litteraire. Exercices tires de textes africains.",
    subject: 'francais',
    niveau: 'seconde',
    teacher: { name: 'Mme Diop' },
    videoUrl: 'https://www.youtube.com/embed/fGO0l4wFe5E',
    durationSec: 780,
    thumbnailUrl: 'https://i.ytimg.com/vi/fGO0l4wFe5E/hqdefault.jpg',
    views: 2670,
    isTrending: true,
    resources: [
      { kind: 'pdf',       title: 'Extrait Une si longue lettre', url: '#' },
      { kind: 'exercices', title: 'Transposition de textes',       url: '#' },
    ],
    chapters: [
      { label: "Regle de l'imparfait",   atSec: 0   },
      { label: 'Regle du passe simple',  atSec: 240 },
      { label: 'Applications',           atSec: 480 },
    ],
  },
  {
    id: 'hub-007',
    title: 'The Simple Present vs Present Continuous',
    description: "Master the difference between simple present habits and present continuous actions. Real-life Dakar examples.",
    subject: 'anglais',
    niveau: '4e',
    teacher: { name: 'M. Mbaye' },
    videoUrl: 'https://www.youtube.com/embed/D23GnMplFHE',
    durationSec: 660,
    thumbnailUrl: 'https://i.ytimg.com/vi/D23GnMplFHE/hqdefault.jpg',
    views: 3450,
    isNew: true,
    resources: [
      { kind: 'pdf',  title: 'Grammar worksheet',     url: '#' },
      { kind: 'quiz', title: 'Fill-in-the-blank quiz', url: '#' },
    ],
    chapters: [
      { label: 'Simple Present',     atSec: 0   },
      { label: 'Present Continuous', atSec: 240 },
      { label: 'Key differences',    atSec: 420 },
      { label: 'Practice exercises', atSec: 540 },
    ],
  },
  {
    id: 'hub-008',
    title: 'Hourouf al-Jarr fil-Lougha al-Arabiyya',
    description: "Explication des prepositions arabes fondamentales et leurs usages dans la phrase arabe.",
    subject: 'arabe',
    niveau: '5e',
    teacher: { name: 'M. Abdallah' },
    videoUrl: 'https://www.youtube.com/embed/b6GcNHM_yoM',
    durationSec: 720,
    thumbnailUrl: 'https://i.ytimg.com/vi/b6GcNHM_yoM/hqdefault.jpg',
    views: 1230,
    resources: [
      { kind: 'pdf',       title: 'Tableau des prepositions arabes', url: '#' },
      { kind: 'exercices', title: 'Exercices pratiques',              url: '#' },
    ],
    chapters: [
      { label: 'Introduction',           atSec: 0   },
      { label: 'Les prepositions',       atSec: 180 },
      { label: 'Exemples coraniques',    atSec: 480 },
    ],
  },
  {
    id: 'hub-009',
    title: 'Les suites arithmetiques et geometriques',
    description: "Definitions, formules du terme general, somme des termes. Applications aux problemes financiers.",
    subject: 'maths',
    niveau: 'premiere',
    teacher: { name: 'M. Diallo' },
    videoUrl: 'https://www.youtube.com/embed/XJP1_i6yGxY',
    durationSec: 1200,
    thumbnailUrl: 'https://i.ytimg.com/vi/XJP1_i6yGxY/hqdefault.jpg',
    views: 3890,
    isTrending: true,
    resources: [
      { kind: 'pdf',       title: 'Formulaire suites',      url: '#' },
      { kind: 'exercices', title: 'Annales BFEM -- suites', url: '#' },
      { kind: 'quiz',      title: 'Quiz auto-correctif',    url: '#' },
    ],
    chapters: [
      { label: 'Suite arithmetique',   atSec: 0   },
      { label: 'Suite geometrique',    atSec: 360 },
      { label: 'Somme des termes',     atSec: 720 },
      { label: 'Exercices annales',    atSec: 960 },
    ],
  },
  {
    id: 'hub-010',
    title: 'La photosynthese -- Bilan et etapes',
    description: "Phase claire, phase sombre, cycle de Calvin. Equation globale et importance ecologique.",
    subject: 'svt',
    niveau: 'terminale',
    teacher: { name: 'Mme Ndiaye' },
    videoUrl: 'https://www.youtube.com/embed/g78utcLQrJ4',
    durationSec: 1020,
    thumbnailUrl: 'https://i.ytimg.com/vi/g78utcLQrJ4/hqdefault.jpg',
    views: 2850,
    resources: [
      { kind: 'pdf',  title: 'Schema cycle de Calvin', url: '#' },
      { kind: 'quiz', title: 'QCM -- photosynthese',   url: '#' },
    ],
    chapters: [
      { label: 'Phase claire',    atSec: 0   },
      { label: 'Cycle de Calvin', atSec: 360 },
      { label: 'Bilan global',    atSec: 720 },
    ],
  },
  {
    id: 'hub-011',
    title: 'Electrostatique -- Loi de Coulomb',
    description: "Charges electriques, force de Coulomb, champ electrique. Exercices avec calcul vectoriel.",
    subject: 'pc',
    niveau: 'terminale',
    teacher: { name: 'M. Sow' },
    videoUrl: 'https://www.youtube.com/embed/x1-SibwIPM4',
    durationSec: 1080,
    thumbnailUrl: 'https://i.ytimg.com/vi/x1-SibwIPM4/hqdefault.jpg',
    views: 2210,
    isNew: true,
    resources: [
      { kind: 'pdf',       title: 'Formulaire electrostatique', url: '#' },
      { kind: 'exercices', title: 'TD electrostatique',          url: '#' },
    ],
    chapters: [
      { label: 'Charges et loi de Coulomb', atSec: 0   },
      { label: 'Champ electrique',           atSec: 420 },
      { label: 'Exercices corriges',         atSec: 780 },
    ],
  },
  {
    id: 'hub-012',
    title: "La colonisation de l'Afrique -- Conference de Berlin",
    description: "Partage de l'Afrique en 1884-85, resistances africaines, impact economique et culturel de la colonisation.",
    subject: 'hg',
    niveau: 'premiere',
    teacher: { name: 'Mme Faye' },
    videoUrl: 'https://www.youtube.com/embed/C7v3rV77oqs',
    durationSec: 1260,
    thumbnailUrl: 'https://i.ytimg.com/vi/C7v3rV77oqs/hqdefault.jpg',
    views: 1780,
    resources: [
      { kind: 'pdf',  title: 'Cartes de la colonisation', url: '#' },
      { kind: 'quiz', title: 'QCM Conference de Berlin',   url: '#' },
    ],
    chapters: [
      { label: "Contexte -- Scramble for Africa", atSec: 0    },
      { label: 'Conference de Berlin',            atSec: 300  },
      { label: 'Resistances africaines',          atSec: 720  },
      { label: 'Bilan et heritages',              atSec: 1020 },
    ],
  },
]
